### ISSUE TITLE
View Project EPDs

### ISSUE THREAD

**Issue by ocni-dtu** [lcacollect/shared-assembly-frontend#2]
Users should be able to see an overview of all EPDs in the project.

```[tasklist]
### Tasks
- [ ] https://github.com/lcacollect/shared-assembly-frontend/issues/9
- [ ] https://github.com/lcacollect/shared-assembly-frontend/issues/10
- [ ] https://github.com/lcacollect/shared-assembly-frontend/issues/11
- [ ] https://github.com/lcacollect/shared-assembly-frontend/issues/12
- [ ] https://github.com/lcacollect/shared-assembly-frontend/issues/13
```
