### ISSUE TITLE
View, Create, Update, Delete Assemblies

### ISSUE THREAD

**Issue by ocni-dtu** [lcacollect/shared-assembly-frontend#5]
As a project member, I should be able to view, create, update and delete assemblies in my project. 
```[tasklist]
### Tasks
- [ ] https://github.com/lcacollect/shared-assembly-frontend/issues/17
- [ ] https://github.com/lcacollect/shared-assembly-frontend/issues/18
- [ ] https://github.com/lcacollect/shared-assembly-frontend/issues/19
```
