### ISSUE TITLE
Connect Assemblies to Building Components

### ISSUE THREAD

**Issue by ocni-dtu** [lcacollect/shared-assembly-frontend#6]
As a project member, I should be able to add project assemblies to building components 
```[tasklist]
### Tasks
- [ ] https://github.com/lcacollect/shared-assembly-frontend/issues/14
- [ ] https://github.com/lcacollect/shared-assembly-frontend/issues/15
- [ ] https://github.com/lcacollect/shared-assembly-frontend/issues/16
```
